-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN (
#             SELECT FOOD_TYPE, MAX(FAVORITES)
#             FROM REST_INFO
#             GROUP BY FOOD_TYPE
#         )
# ORDER BY FOOD_TYPE DESC;

# WITH RankedRest AS (
#     SELECT 
#         FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
#         ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC, REST_ID) AS rnk
#     FROM REST_INFO
# )
# SELECT 
#     FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM RankedRest
# WHERE rnk = 1
# ORDER BY FOOD_TYPE DESC;
WITH RANKED AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RANKED
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC;




