-- 코드를 작성해주세요
WITH MAXI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(e.DIFFERENTIATION_DATE), m.MAX - e.SIZE_OF_COLONY AS YEAR_DEV, e.ID
FROM ECOLI_DATA e JOIN MAXI m ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV;