WITH M AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY I.ID;

# WITH RANKED AS (
#     SELECT ID, FISH_TYPE, LENGTH,
#     MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS rnk
#     FROM FISH_INFO
# )
WITH RANKED AS (
    SELECT ID, FISH_TYPE, LENGTH,
    RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rnk
    FROM FISH_INFO
)
SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM RANKED i JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
WHERE rnk = 1
ORDER BY i.ID ASC;

