-- 코드를 작성해주세요
SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_GRADE g , HR_EMPLOYEES e 
WHERE g.EMP_NO = e.EMP_NO AND g.YEAR = 2022
GROUP BY EMP_NO 
ORDER BY SCORE DESC LIMIT 1;