-- 코드를 입력하세요
SELECT u.TITLE, u.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS,
DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD u JOIN USED_GOODS_REPLY r
ON u.BOARD_ID = r.BOARD_ID
where u.CREATED_DATE like '2022-10%'
order by r.CREATED_DATE asc, u.TITLE asc;